use_frameworks!

target 'LJTimerBlockManager_Example' do
  pod 'LJTimerBlockManager', :path => '../'

  target 'LJTimerBlockManager_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  end
end
